### ISSUE TITLE
Fails to build wheel for Python 3.10

### ISSUE THREAD

**Issue by uranusjr** [pypa/wheel#354] opened 2020-05-23 13:23 UTC
Encountered while looking into pypa/pip#8312.

```
$ python --version  # Built from master.
Python 3.10.0a0
$ python -c 'import setuptools; print(setuptools.__version__)'
46.0.0
$ python -m pip install --no-build-isolation -U "wheel @ git+https://github.com/pypa/wheel.git"
...
Successfully installed wheel-0.34.2
$ git clone https://github.com/cython/cython.git
$ cd cython
$ python setup.py bdist_wheel
...
running install_scripts
Traceback (most recent call last):
  File "cython/setup.py", line 291, in <module>
    run_build()
  File "cython/setup.py", line 228, in run_build
    setup(
  File "pip-8312/lib/python3.10/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "python3.10/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "python3.10/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "python3.10/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "pip-8312/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 328, in run
    impl_tag, abi_tag, plat_tag = self.get_tag()
  File "/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
    assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
AssertionError: would build wheel with unsupported tag ('cp310', 'cp310', 'linux_x86_64')
```

It seems like `bdist_wheel` is using different tag schemes to build and check the tags. The assertion uses `packaging.tags`, which correctly tag Python 3.10 as `cp3_10` (see pypa/packaging#240), but the build part incorrectly tries to use `cp310`, causing the assertion error.

---

Side note: The sdist has a packaging issue. `--no-build-isolation` is needed since otherwise the build fails with `ModuleNotFoundError: No module named 'packaging'`.

**Comment by mattip** [comment] 2020-05-23 18:17
I think this should be fixed by gh-346 which changes wheel to use packaging underneath. Could you check what happens if you `python -m pip install git+https://github.com/pypa/wheel@master which should install a newer wheel then try to build your package's wheel?

**Comment by uranusjr** [comment] 2020-05-23 18:23
The assertion error is *introduced* by #346. Prior to the patch, `bdist_wheel` would “successfully” produce a wheel with an invalid tag `Cython-3.0a5-cp310-cp310-linux_x86_64.whl`. After the patch, `wheel` uses the same logic as before to generate the wheel tags, but the assertion prevents the actual wheel generation because it correctly identifies that the wheel tags would be invalid.

**Comment by mattip** [comment] 2020-05-23 19:08
Thanks for the clarification. I think this is coming from `sysconfig.get_config_var('py_version_nodot')` which is called by `tags.interpreter_version()` which is called by `bdist_wheel`. Could you check whether `sysconfig.get_config_var('py_version_nodot')` is `310` or `3_10` ?

**Comment by uranusjr** [comment] 2020-05-23 19:39
`sysconfig.get_config_var('py_version_nodot')` returns `310`.

**Comment by mattip** [comment] 2020-05-23 20:19
:(. I opened the linked issue in packaging, since it is a CPython problem it will be tricky to fix.

**Comment by dimaqq** [comment] 2020-10-13 00:35
Kind ping, since Python-3.10.0a1 is out, and it would be awesome to test our code and oss libraries, but a few can't be built😭

**Comment by pquentin** [comment] 2020-10-13 05:15
@dimaqq I think https://github.com/python/cpython/pull/20333 needs to be merged first

**Comment by agronholm** [comment] 2020-10-13 05:16
Yeah, doesn't seem worthwhile to fix this from the wheel side.

**Comment by markshannon** [comment] 2020-12-09 18:26
Why does pip use a text decimal version, rather the tuple of numbers from `sys.version_info`?
It does seem rather fragile?

https://github.com/pypa/wheel/blob/64550e15fdbc96d5690dc872257edc859c218068/src/wheel/vendored/packaging/tags.py#L815

**Comment by mattip** [comment] 2020-12-09 18:49
So avoid the `310` vs `3_10` problem altogether by always using (3, 10) instead? Interesting. I wish I would have thought of that 6 months ago. :)

**Comment by mattip** [comment] 2020-12-09 18:50
Since both pip and wheel vendor in versions of packaging, they might be able to deal with an ABI-breaking change.

**Comment by domdfcoding** [comment] 2020-12-12 09:11
https://github.com/pypa/packaging/pull/355 has now been merged, and is included in included in the 20.8 release. I think that should fix this issue. It will just need a new version of wheel with the latest packaging vendored.

**Closed** 2020-12-13 12:21 UTC

**Comment by RhinosF1** [comment] 2020-12-13 13:11
> a new version of wheel

Do we know when this is due out?

**Comment by mattip** [comment] 2020-12-13 13:14
Probably in a day or two, judging by [this comment](https://github.com/pypa/wheel/pull/390#issuecomment-743992197). But these things take time, there are usually last-minute snags.

**Comment by agronholm** [comment] 2020-12-13 18:10
I've released v0.36.2 now.

**Comment by RhinosF1** [comment] 2020-12-13 18:17
> I've released v0.36.2 now.

Working for me now with 3.10 alpha 3

Yey!

**Comment by frenzymadness** [comment] 2021-02-10 11:29
Hello, I might find a regression in the latest releases. Is that a problem in the wheel or somewhere else or is it just me doing something wrong?

```
# pip list 
Package    Version
---------- -------
pip        21.0.1
setuptools 53.0.0
wheel      0.36.2

# python -V
Python 3.10.0a5

# pip install numpy
Collecting numpy
  Using cached numpy-1.20.1.zip (7.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: numpy
  Building wheel for numpy (PEP 517) ... error
… very long output …
AssertionError: would build wheel with unsupported tag ('cp310', 'cp310', 'linux_x86_64')
…
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
```

**Comment by uranusjr** [comment] 2021-02-10 11:43
Can you post the “very long output” part?

**Comment by fochoao** [comment] 2021-02-10 11:51
This works for Windows 10, prebuilt binaries, wheel totally working on alpha 5. https://github.com/fochoao/cpython

**Comment by agronholm** [comment] 2021-02-10 12:12
The scientific Python stack is notorious for their home grown packaging tools, so this might be a problem with an outdated, vendored wheel.

**Comment by agronholm** [comment] 2021-02-10 13:20
I was right: https://github.com/numpy/numpy/blob/master/pyproject.toml#L5

**Comment by uranusjr** [comment] 2021-02-10 13:47
Seems like they’re choosing the upper version cap to make sure the build environment is predictable. I think they’d be very willing to update the declaration if you raise the issue to them.

**Comment by frenzymadness** [comment] 2021-02-10 14:08
Thank you all, I'm gonna propose a fix there!

**Comment by fochoao** [comment] 2021-05-05 07:16
Check out my cpython build, I got wheel fully running in https://github.com/fochoao/cpython however all is compiled mostly for Windows 10.

**Comment by The-Compiler** [comment] 2021-05-05 07:49
@fochoao Let me note that (at least for x86 and x86_64), official [release binaries](https://www.python.org/downloads/release/python-3100b1/) are available. This has nothing to do with building wheels of Python packages (which this issue is about), however.

**Comment by fochoao** [comment] 2021-05-05 19:41
> @fochoao Let me note that (at least for x86 and x86_64), official [release binaries](https://www.python.org/downloads/release/python-3100b1/) are available. This has nothing to do with building wheels of Python packages (which this issue is about), however.

Try https://github.com/python/cpython/ for the real deal. Hope that helps.
