### ISSUE TITLE
Package description is corrupted when a line starts with "From "

### ISSUE THREAD

**Issue by jobec** [pypa/wheel#189] opened 2017-08-31 08:46 UTC
When a wheel is build and the file `METADATA` is written, all lines starting with `From ` are prefixed with a `>`. For example, [this line of my README file](https://github.com/jobec/rfc5424-logging-handler/blame/07dbbe63f9a08ba962587dbab796cb0d62c34971/README.rst#L133) is changed from
```
From a logging config dictionary
```
into
```
>From a logging config dictionary
```
Turning it into invalid reStructuredText. This description ends up in the file `DESCRIPTION.rst` and eventually turned my package description on PyPi into garbage.

I traced the issue back to [this specific line](https://github.com/python/cpython/blob/d0e61bded5256e775e470e2c0da22367a1a81970/Lib/email/generator.py#L245) in the standard python `email.generator` module.

Of course, rewriting that section title fixes things, but this is one hell of a nasty bug to bump into. Nobody expects his package description to be handled like and email 🤔

**Comment by jobec** [comment] 2017-08-31 08:50
Combined with https://github.com/pypa/warehouse/issues/2170 this is quite a P.I.T.A.

**Comment by dholth** [comment] 2017-09-01 20:25
Can we simply pass mangle_from=False to the Generator()

**Comment by agronholm** [comment] 2017-09-03 11:05
This has already been fixed in master.

**Closed** 2017-09-03 11:05 UTC
Labels: duplicate

**Comment by agronholm** [comment] 2017-09-03 11:09
Duplicate of #178.
