### ISSUE TITLE
Failed building wheel @ macoOS & Python 3.10.0

### ISSUE THREAD

**Issue by felixdivo** [pypa/wheel#382] opened 2020-11-26 10:02 UTC
In [this](https://github.com/hardbyte/python-can/pull/940/checks?check_run_id=1458088499#step:4:92) job on github workflows, we have this error:

```
Failed to build lazy-object-proxy
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.10
  creating build/lib.linux-x86_64-3.10/lazy_object_proxy
  copying src/lazy_object_proxy/__init__.py -> build/lib.linux-x86_64-3.10/lazy_object_proxy
  copying src/lazy_object_proxy/slots.py -> build/lib.linux-x86_64-3.10/lazy_object_proxy
  copying src/lazy_object_proxy/compat.py -> build/lib.linux-x86_64-3.10/lazy_object_proxy
  copying src/lazy_object_proxy/utils.py -> build/lib.linux-x86_64-3.10/lazy_object_proxy
  copying src/lazy_object_proxy/simple.py -> build/lib.linux-x86_64-3.10/lazy_object_proxy
  copying src/lazy_object_proxy/_version.py -> build/lib.linux-x86_64-3.10/lazy_object_proxy
  running build_ext
  building 'lazy_object_proxy.cext' extension
  creating build/temp.linux-x86_64-3.10
  creating build/temp.linux-x86_64-3.10/src
  creating build/temp.linux-x86_64-3.10/src/lazy_object_proxy
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/lazy_object_proxy -I/opt/hostedtoolcache/Python/3.10.0-alpha.2/x64/include/python3.10 -c src/lazy_object_proxy/cext.c -o build/temp.linux-x86_64-3.10/src/lazy_object_proxy/cext.o
  gcc -pthread -shared -Wl,--rpath=/opt/hostedtoolcache/Python/3.10.0-alpha.2/x64/lib -Wl,--rpath=/opt/hostedtoolcache/Python/3.10.0-alpha.2/x64/lib build/temp.linux-x86_64-3.10/src/lazy_object_proxy/cext.o -L/opt/hostedtoolcache/Python/3.10.0-alpha.2/x64/lib -o build/lib.linux-x86_64-3.10/lazy_object_proxy/cext.cpython-310-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/lazy_object_proxy
  copying build/lib.linux-x86_64-3.10/lazy_object_proxy/cext.cpython-310-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/lazy_object_proxy
  copying build/lib.linux-x86_64-3.10/lazy_object_proxy/__init__.py -> build/bdist.linux-x86_64/wheel/lazy_object_proxy
  copying build/lib.linux-x86_64-3.10/lazy_object_proxy/slots.py -> build/bdist.linux-x86_64/wheel/lazy_object_proxy
  copying build/lib.linux-x86_64-3.10/lazy_object_proxy/compat.py -> build/bdist.linux-x86_64/wheel/lazy_object_proxy
  copying build/lib.linux-x86_64-3.10/lazy_object_proxy/utils.py -> build/bdist.linux-x86_64/wheel/lazy_object_proxy
  copying build/lib.linux-x86_64-3.10/lazy_object_proxy/simple.py -> build/bdist.linux-x86_64/wheel/lazy_object_proxy
  copying build/lib.linux-x86_64-3.10/lazy_object_proxy/_version.py -> build/bdist.linux-x86_64/wheel/lazy_object_proxy
  running install_egg_info
  running egg_info
  writing src/lazy_object_proxy.egg-info/PKG-INFO
  writing dependency_links to src/lazy_object_proxy.egg-info/dependency_links.txt
  writing top-level names to src/lazy_object_proxy.egg-info/top_level.txt
  reading manifest file 'src/lazy_object_proxy.egg-info/SOURCES.txt'
  writing manifest file 'src/lazy_object_proxy.egg-info/SOURCES.txt'
  Copying src/lazy_object_proxy.egg-info to build/bdist.linux-x86_64/wheel/lazy_object_proxy-1.4.3-py3.10.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.10.0-alpha.2/x64/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/opt/hostedtoolcache/Python/3.10.0-alpha.2/x64/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/hostedtoolcache/Python/3.10.0-alpha.2/x64/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-36mbg09a/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 216, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-36mbg09a/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-36mbg09a/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-36mbg09a/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 61, in <module>
      setup(
    File "/tmp/pip-build-env-36mbg09a/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/opt/hostedtoolcache/Python/3.10.0-alpha.2/x64/lib/python3.10/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/hostedtoolcache/Python/3.10.0-alpha.2/x64/lib/python3.10/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/hostedtoolcache/Python/3.10.0-alpha.2/x64/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-36mbg09a/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 328, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/tmp/pip-build-env-36mbg09a/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 278, in get_tag
      assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
  AssertionError: would build wheel with unsupported tag ('cp310', 'cp310', 'linux_x86_64')
  ----------------------------------------
  ERROR: Failed building wheel for lazy-object-proxy
ERROR: Could not build wheels for lazy-object-proxy which use PEP 517 and cannot be installed directly
```

The versions of the tools are: macos-latest (which [apparently](https://github.com/actions/virtual-environments#available-environments) is macOS version 10.15; so maybe it is unrelated to #381), The Python version is 3.10.0-alpha.2.

I came here from https://github.com/ionelmc/python-lazy-object-proxy/issues/46.

**Comment by agronholm** [comment] 2020-11-26 10:11
Duplicate of #354.

**Closed by agronholm** 2020-11-26 10:11 UTC
