### ISSUE TITLE
black cannot reformat bdist_wheel.py

### ISSUE THREAD

**Issue by dnltsk** [pypa/wheel#425] opened 2021-11-03 23:58 UTC
Unfortunately, `black` is not capable reformatting the `bdist_wheel.py`
```
$ pipenv run black .
error: cannot format /Users/me/my_project/venv/lib/python3.8/site-packages/wheel/bdist_wheel.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/psf/black/issues.  This diff might be helpful: /var/folders/_k/_q2q_p6d5pl82hh8c3t8c1bd_9_w_x/T/blk_7ww1wty0.log
Oh no! 💥 💔 💥
555 files left unchanged, 1 file failed to reformat.
```

Unfortunately I cannot say what version is used because the wheel-package is not mentioned in the `Pipfile.lock` at all.

**Comment by agronholm** [comment] 2021-11-04 07:51
Why are you trying to reformat wheel with black, and why are you reporting this as a bug?

**Comment by ichard26** [comment] 2021-11-11 18:10
Yeah... you really shouldn't be running black against a virtual environment. Anyhow I can't reproduce with black 21.10b0. Let's close this because even if this was a bug, it'd be psf/black who needs to know.

**Closed** 2021-12-22 11:48 UTC
