### ISSUE TITLE
Wheel tool generates broken wheels with two sets of metadata referring to different releases

### ISSUE THREAD

**Issue by dr-leo** [pypa/wheel#210] opened 2017-12-16 15:06 UTC
When building my pure Python project with

>>> python setup.py build sdist bdist_wheel

the wheel contains two sets of metadata: one for the version specified in setup.py, say, 0.8, one for the previously built version, say, 0.7.0. I consider such wheel as broken. It messes up the deployment process: 

When I attempt to deploy the sdist and wheel on pypi, v0.8 is correctly registered, and the sdist is properly uploaded and published. But twine tells warehouse to place the broken whel in the 0.7 release. 

See 
https://github.com/pypa/warehouse/issues/2675

for more details.

I don't even know how to clean up the resulting mess as I cannot upload the wheel for 0.8 to the right place as warehouse complains that there is already the same wheel. I'd have to remove the 0.8 wheel from the 0.7 release page etc. 

I would be surprised if I were the first to report this as my dev cycle should be normal. Well, I tend to forget bumping the version to something like 0.8dev after a release. But I do not think this should confuse the tool chain.

I have opened a related issue at
https://github.com/pypa/twine/issues/284

**Comment by di** [comment] 2017-12-19 15:36
Just wanted to chime in here. @dr-leo was able to build [a somewhat strange wheel](https://files.pythonhosted.org/packages/bd/e7/95de89989549e9ea1e7853eb3679dac98aeb357a629d9633159b1828128a/pandaSDMX-0.8-py2.py3-none-any.whl) which contained metadata for two different versions:

```
$ tar -xvvf pandaSDMX-0.8-py2.py3-none-any.whl
x pandasdmx/agencies.json
x pandasdmx/api.py
x pandasdmx/model.py
x pandasdmx/remote.py
x pandasdmx/__init__.py
x pandasdmx/reader/sdmxjson.py
x pandasdmx/reader/sdmxml.py
x pandasdmx/reader/__init__.py
x pandasdmx/utils/aadict.py
x pandasdmx/utils/anynamedtuple.py
x pandasdmx/utils/__init__.py
x pandasdmx/writer/data2pandas.py
x pandasdmx/writer/structure2pd.py
x pandasdmx/writer/__init__.py
x pandaSDMX-0.7.0.dist-info/DESCRIPTION.rst
x pandaSDMX-0.7.0.dist-info/metadata.json
x pandaSDMX-0.7.0.dist-info/top_level.txt
x pandaSDMX-0.7.0.dist-info/zip-safe
x pandaSDMX-0.8.dist-info/DESCRIPTION.rst
x pandaSDMX-0.8.dist-info/metadata.json
x pandaSDMX-0.8.dist-info/top_level.txt
x pandaSDMX-0.8.dist-info/zip-safe
x pandaSDMX-0.7.0.dist-info/WHEEL
x pandaSDMX-0.8.dist-info/WHEEL
x pandaSDMX-0.7.0.dist-info/METADATA
x pandaSDMX-0.8.dist-info/METADATA
x pandaSDMX-0.7.0.dist-info/RECORD
x pandaSDMX-0.8.dist-info/RECORD
```

Twine misinterpreted the version for this wheel and it was uploaded to PyPI under the wrong release.

It seems like the bug is in wheel, have any of the @pypa/wheel-committers seen this before? Any ideas about what might have gone wrong?

**Comment by agronholm** [comment] 2017-12-19 15:59
I've never heard of a problem like this. How did @dr-leo do this?

**Comment by di** [comment] 2017-12-19 16:21
From pypa/warehouse#2675:

> After bumping the version in setup.py to 0.8, I did the usual
>
> `>> python Setup.py build sdist bdist_wheel`
>
> However, the build subdir contained previous builds. And there was an
egg.info as usual.

Also:

> Environment:
>
> Win7x64, Py3.5 32bit, Wheel 29.0, twine 1.9.1.

**Comment by agronholm** [comment] 2017-12-19 16:25
I will try to reproduce this and get back to you.

**Comment by agronholm** [comment] 2017-12-19 16:25
I should note that this could be related to #147.

**Comment by dr-leo** [comment] 2017-12-20 10:20
Btw: The resulting Wheel cannot be installed:
https://github.com/dr-leo/pandaSDMX/issues/60

**Comment by dr-leo** [comment] 2017-12-21 05:35
I use a conda env. Should not be relevant though.

**Comment by agronholm** [comment] 2018-03-30 09:17
@dr-leo I cannot reproduce this locally. If you provide clear instructions from reproducing from a git clone, I can investigate this further.

**Comment by agronholm** [comment] 2018-03-31 19:32
@di could not reproduce this either. I will have to defer this to a future release.

**Comment by di** [comment] 2018-04-19 12:45
From https://github.com/pypa/warehouse/issues/2675:

> I have set up a repo demonstrating the bug:
> 
> https://github.com/dr-leo/wheelbug
> 
> It contains the build and dist dirs as well as egg.info.
> 
> It has two commits: The first is a snapshot at v0.9. The wheel is
> buggy as it also contains the distinfo for the previous v0.8.2. The
> 2nd commit captures the state after building v0.10. The new wheel
> contains three distinfos, namely for 0.8.2, 0.9 and 0.10. It looks
> like this appending business could continue forever.
> 
> Hope this helps to reproduce the bug or at least to add a sanity check
> to warehouse.
> 
> That said, I would love to see the build toolchain fixed to avoid
> building such insane wheels in the first place.

**Comment by di** [comment] 2018-04-19 12:45
@dr-leo I was not able to reproduce your issue, however I don't have a Windows machine to test on, and I suspect that might be part of the cause.

Can you do the following from the root of your example repo:
* remove the `build` and `dist` directories
* build a wheel
* is there anything in the `build/bdist.win32` directory?

**Comment by agronholm** [comment] 2018-07-16 18:54
It doesn't look like @dr-leo is going to answer. I'll reopen this if the situation changes, but since nobody can reproduce this, I'm closing the issue.

**Closed by agronholm** 2018-07-16 18:54 UTC
