### ISSUE TITLE
RECORD file generation should be idempotent 

### ISSUE THREAD

**Issue by af6140** [pypa/wheel#229] opened 2018-03-06 02:04 UTC
The generated RECORD file entries order may vary between runs. This causes problem when deploying aws lambda package, since the checksum changes.

**Comment by agronholm** [comment] 2018-03-28 21:14
I find this odd given that directories and file names are sorted while walking the directory tree. Can you consistently reproduce this problem?

**Comment by agronholm** [comment] 2018-03-29 09:18
@af6140 I will fix this by the end of the week if you have time to work with me on this. Otherwise I will move this to the next release.

**Comment by agronholm** [comment] 2018-03-31 11:47
I'm still willing to fix this but it'll have to wait until the next release.

**Comment by af6140** [comment] 2018-04-03 19:58
Was out of town, ok to fix in next release.

**Comment by agronholm** [comment] 2018-04-03 20:15
But I still have no idea how to reproduce the problem. Please provide instructions.

**Comment by agronholm** [comment] 2018-05-13 16:59
Cannot reproduce and OP has not responded in 5 weeks so I'm closing this. Comment if you feel this is wrong.

**Closed by agronholm** 2018-05-13 16:59 UTC

**Comment by dholth** [comment] 2018-05-15 12:28
Possibly they are using an old version.
