### ISSUE TITLE
Wheel failed include data_file

### ISSUE THREAD

**Issue by atya5** [pypa/wheel#214] opened 2018-01-07 03:54 UTC
I created a  wheel using python3.4 install bdist_wheel command.

I have data dir and in contains files Test.png.

in setup.py I added
data_files=[
        ('/usr/share', ['data/Test.png'])
        ]

when I am installing the wheel the data files did not copy.

**Comment by bennofs** [comment] 2018-03-16 07:05
Absolute paths in `data_files` don't work with wheels, see https://github.com/pypa/wheel/issues/92 and relative paths behave differently depending on if you're using wheels or not, so I recommend avoiding `data_files`. You may want to use `package_data` instead.

**Comment by agronholm** [comment] 2018-03-22 20:01
Yeah, this is either invalid or a duplicate of #92.

**Closed by agronholm** 2018-03-22 20:01 UTC
Labels: duplicate
